// Mocks generated by Mockito from annotations
// in maphi_contas/test/auth/domain/usecases/sign_in_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i3;

import 'package:fpdart/fpdart.dart' as _i4;
import 'package:maphi_contas/auth/domain/entities/google_user.dart' as _i6;
import 'package:maphi_contas/auth/domain/repositories/auth_repository_interface.dart'
    as _i2;
import 'package:maphi_contas/core/domain/entities/app_failure.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AuthRepositoryInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepositoryInterface extends _i1.Mock
    implements _i2.AuthRepositoryInterface {
  @override
  _i3.Future<_i4.Either<_i5.AppFailure, _i6.GoogleUser>> signIn() =>
      (super.noSuchMethod(
        Invocation.method(#signIn, []),
        returnValue:
            _i3.Future<_i4.Either<_i5.AppFailure, _i6.GoogleUser>>.value(
              _i7.dummyValue<_i4.Either<_i5.AppFailure, _i6.GoogleUser>>(
                this,
                Invocation.method(#signIn, []),
              ),
            ),
        returnValueForMissingStub:
            _i3.Future<_i4.Either<_i5.AppFailure, _i6.GoogleUser>>.value(
              _i7.dummyValue<_i4.Either<_i5.AppFailure, _i6.GoogleUser>>(
                this,
                Invocation.method(#signIn, []),
              ),
            ),
      ) as _i3.Future<_i4.Either<_i5.AppFailure, _i6.GoogleUser>>);

  @override
  _i3.Future<_i4.Either<_i5.AppFailure, _i6.GoogleUser>> signOut() =>
      (super.noSuchMethod(
        Invocation.method(#signOut, []),
        returnValue:
            _i3.Future<_i4.Either<_i5.AppFailure, _i6.GoogleUser>>.value(
              _i7.dummyValue<_i4.Either<_i5.AppFailure, _i6.GoogleUser>>(
                this,
                Invocation.method(#signOut, []),
              ),
            ),
        returnValueForMissingStub:
            _i3.Future<_i4.Either<_i5.AppFailure, _i6.GoogleUser>>.value(
              _i7.dummyValue<_i4.Either<_i5.AppFailure, _i6.GoogleUser>>(
                this,
                Invocation.method(#signOut, []),
              ),
            ),
      ) as _i3.Future<_i4.Either<_i5.AppFailure, _i6.GoogleUser>>);
}
